import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";
import {
  Heading,
  Hero,
  Companies,
  Product,
  Numbers,
  Mobile,
  Testimonials,
} from "../components";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Manta</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Hero />
        <Companies />
        <Product />
        <Numbers />
        <Heading title="We are helping customers globally" />
        <Mobile />
        <Heading title="Some words from our clients" />
        <Testimonials />
      </main>
    </>
  );
}
